language: python
python:
- '3.6'
services:
  - postgresql
before_script:
- pip3 install -r requirements.txt
- psql -c 'create database test;' -U postgres
- psql -c 'create database fastfood;' -U postgres
- export FLASK_ENV=development
script:
- pytest -v --cov app --cov-report term-missing
after_success:
- coveralls